import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    // images/** is in-container code (CommonJS, its own package.json + Node
    // runtime), not part of the monorepo's TS lint scope.
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/next-env.d.ts', // generated by Next.js
      '**/node_modules/**',
      'images/**',
      '.swarm_data/**', // persistent agent disks — not our source
      'start.mjs', // container entrypoint (Node runtime, not part of the TS app)
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Keep ESLint out of formatting's lane — Prettier owns that.
  prettier,
);
