// Friendly, human first names for agents (e.g. "alice", "bob"). A curated list
// rather than a generator dictionary — keeps them clean and recognizable.
const NAMES = [
  'alice',
  'bob',
  'carly',
  'david',
  'evan',
  'frank',
  'grace',
  'henry',
  'ivy',
  'jack',
  'kate',
  'leo',
  'mia',
  'noah',
  'olivia',
  'peter',
  'quinn',
  'rosa',
  'sam',
  'tara',
  'victor',
  'wendy',
  'xander',
  'yara',
  'zoe',
  'clara',
  'derek',
  'elena',
  'felix',
  'george',
  'hannah',
  'isaac',
  'julia',
  'kevin',
  'luna',
  'marco',
  'nora',
  'oscar',
  'paula',
  'ruby',
  'simon',
  'tessa',
  'uma',
  'vince',
  'willa',
  'arthur',
  'bella',
  'caleb',
  'diana',
  'emil',
  'fiona',
  'gus',
  'hazel',
  'ian',
  'josie',
  'karl',
  'lena',
  'milo',
  'nina',
  'omar',
  'piper',
  'rhea',
  'theo',
  'vera',
  'walter',
  'cleo',
  'dexter',
  'elsa',
  'fred',
  'greta',
  'hugo',
  'iris',
  'jonas',
  'kira',
  'lucas',
  'maya',
  'nate',
  'opal',
  'percy',
  'rosie',
  'stella',
  'toby',
  'ursula',
  'wade',
  'yusuf',
  'zara',
  'anna',
  'ben',
  'cora',
  'dylan',
];

/**
 * A random friendly first name, e.g. "alice", that isn't already taken by an
 * existing agent. Returns null when every name in the list is in use (so the
 * caller can warn the user to type one manually).
 */
export function randomName(taken: Iterable<string> = []): string | null {
  const used = new Set([...taken].map((s) => s.trim().toLowerCase()));
  const free = NAMES.filter((n) => !used.has(n));
  if (free.length === 0) return null;
  return free[Math.floor(Math.random() * free.length)]!;
}
